site_name: LoongArch Python Packages CI
site_url: https://loongson-cloud-community.github.io/pypi/
theme:
  name: material
nav:
  - ğŸ¡ Home: index.md
  - ğŸ› ï¸ User Guide: user-guide.md
  - âš™ï¸ CI Details: ci-details.md
  - ğŸ¤ Contributing: contributing.md
  - ğŸ“š Package List: package-list.md
  - â“ FAQ: faq.md
  - ğŸ“ Changelog: changelog.md

