name: build cmake wheel

on:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/cmake.yaml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/cmake.yaml"
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'latest'
env:
  PACKAGE: cmake 
jobs:
  build:
    name: Build cmake ${{ matrix.platform }} wheel on loongarch64
    runs-on: ${{ matrix.os }}
    outputs:
      upload: ${{ steps.check.outputs.upload }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        platform: ["manylinux", "musllinux"]
    steps:
      - name: Check if exists
        id: check
        run: |
          pkg=cmake

          skip=false
          upload=false

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            version="${{ github.event.inputs.version }}"
          else
            version="latest"
          fi

          platform="${{ matrix.platform }}"
          url="https://lpypi.loongnix.cn/loongson/pypi/+simple/${pkg}/"
          upstream_url="https://api.github.com/repos/scikit-build/cmake-python-distributions/releases/latest"

          if [[ "${version}" == "latest" ]]; then
            version="$(curl -s ${upstream_url} | jq -r .tag_name)"
          fi

          if curl -Ls ${url} | grep -q ${pkg}-${version}-.*${platform}.*loongarch64; then
            skip=true
            upload=false
            echo "${platform} wheels already exists."
          else
            skip=false
            upload=true
            echo "${platform} wheels not found, continue building"
          fi

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            skip=false
            upload=false
          fi

          echo "VERSION=${version}" >> $GITHUB_ENV
          echo "SKIP=${skip}" >> $GITHUB_ENV
          echo "UPLOAD=${upload}" >> $GITHUB_OUTPUT


      - name: Download source
        if: ${{ env.SKIP != 'true' }}
        uses: actions/checkout@v6
        with:
          repository: scikit-build/cmake-python-distributions
          ref: ${{ env.VERSION }}
          fetch-depth: 0

      - name: Setup env
        if: ${{ env.SKIP != 'true' }}
        run: |
          case "${{ matrix.platform }}" in
            manylinux)
              echo CIBW_SKIP="*-musllinux_loongarch64" >> $GITHUB_ENV
              ;;
            musllinux)
              echo CIBW_SKIP="*-manylinux_loongarch64" >> $GITHUB_ENV
              ;;
          esac

          sed -i 's/"cmake.define.RUN_CMAKE_TEST" = "ON"/"cmake.define.RUN_CMAKE_TEST" = "OFF"/g' pyproject.toml
          sed -i '/s390x) GO_ARCH=s390x;;/a \        loongarch64) GO_ARCH=loong64;;' scripts/install-static-clang.sh

      - name: Setup QEMU
        if: ${{ env.SKIP != 'true' }}
        uses: docker/setup-qemu-action@v3

      - name: Build wheel
        if: ${{ env.SKIP != 'true' }}
        uses: loong64/cibuildwheel@v3.3.1
        env:
          PIP_INDEX_URL: "https://lpypi.loongnix.cn/loongson/pypi/+simple"
          CIBW_ARCHS: "loongarch64"
          CIBW_BUILD: "cp310-${{ matrix.platform }}_*"
          CIBW_ENVIRONMENT_PASS_LINUX: >
            PIP_INDEX_URL

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE }}-${{ env.VERSION }}-${{ matrix.platform }}
          path: wheelhouse/*

  upload:
    needs: [build]
    runs-on: ${{ matrix.os }}
    if: needs.build.outputs.upload == 'true' && github.event_name != 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        os: [loongarch64-abi2.0]
        platform: ["manylinux"]

    steps:
      - name: Clean workspace
        run: safe-rm -rf * .*

      - uses: actions/download-artifact@v4
        with:
          pattern: ${{ env.PACKAGE }}-*
          path: wheelhouse
          merge-multiple: true

      - name: Upload wheels
        run: |
          ls wheelhouse/${{ env.PACKAGE }}-*.whl || exit 1
          pip install twine==6.0.1
          twine upload --repository-url https://lpypi.loongnix.cn/loongson/pypi wheelhouse/${{ env.PACKAGE }}-*.whl
        env:
          TWINE_USERNAME: ${{ secrets.INDEX_NAME }}
          TWINE_PASSWORD: ${{ secrets.INDEX_TOKEN }}

